### ISSUE TITLE
${ux_ehci_ed_microframe_ssplit_count} is not calculated correctly

### ISSUE THREAD

**Issue by xuzihan351** [eclipse-threadx/usbx#108] opened 2023-06-27 07:13 UTC
I am using USBX host to access the mouse device. I found that some mouse insertion and removal operations caused the program to enter a hard fault. 
I have found that as long as the device has multiple interrupt endpoints, this situation will occur.
So I tracked the correlation function of the interrupt endpoint. I found that in the `ux_hcd_ehci_interrupt_endpoint_destroy` function, the value of this variable changed from 0 to 255. When the device is plugged in again, `_ux_host_stack_new_device_create` will return `UX_NO_BANDWIDTH_AVAILABLE` because of the `ux_ehci_ed_microframe_ssplit_count == 255`.
So I add a `if ux_ehci_ed_microframe_ssplit_count > 0` before the `ux_ehci_ed_microframe_ssplit_count--`, the bug has disapperared.
Please check this error and let me know the correct repair method.

**Comment by xiaocq2001** [comment] 2023-06-30 02:00
Hi, please try change `interval` in following lines to `8`:

https://github.com/azure-rtos/usbx/blob/ef2fa7717be8ab751fdfb5d3f91e24fbbaea8dd6/common/usbx_host_controllers/src/ux_hcd_ehci_interrupt_endpoint_create.c#L269

https://github.com/azure-rtos/usbx/blob/ef2fa7717be8ab751fdfb5d3f91e24fbbaea8dd6/common/usbx_host_controllers/src/ux_hcd_ehci_interrupt_endpoint_create.c#L296

and check if that helps to remove the split count check.

**Comment by xuzihan351** [comment] 2023-06-30 02:23
It also result in an exception.
![image](https://github.com/azure-rtos/usbx/assets/56530060/2db6527f-dc56-4a6e-877e-9e77d3f3173f)

**Comment by xiaocq2001** [comment] 2023-06-30 06:10
Thanks for the feedback.
I think we may need more time to find out what's the root cause.
In normal case, `ux_ehci_ed_microframe_ssplit_count` is increased on endpoint creating and decreased on endpoint destroy.

**Comment by xuzihan351** [comment] 2023-06-30 06:50
I tested several mice and tracked the process of creating interrupt endpoints.
For mouses with interrupt reporting cycles longer than 1 millisecond, `ux_ehci_ed_microframe_ssplit_count` will not increase during endpoiint creating. But it will decrease during destory.

**Comment by xiaocq2001** [comment] 2023-06-30 07:35
https://github.com/azure-rtos/usbx/blob/7c928b43db68b72970b3effd5a2582eb5a6869c7/common/usbx_host_controllers/src/ux_hcd_ehci_interrupt_endpoint_create.c#L243
`interval` calculation is not correct, if endpoint interval is larger than 1ms, final checked `interval` in code should be 8. Please try following code:

```
    /* Keep interval <= 1ms for micro-frame calculation.  */
    /* Make it index steps to move.  */
    if (interval >= 4)
    {
        interval = 3; /* Uses 3 for 1ms calculation.  */
    }
    else if (interval > 0)
    {
        interval --;
        interval &= 0x3;
    }
    interval = (1u << interval); /* 1 (1/8ms), 2, 4, 8 (1ms)  */
```

**Comment by xuzihan351** [comment] 2023-06-30 07:39
It works!

**Comment by xiaocq2001** [comment] 2023-06-30 07:42
Glad to hear that.

**Comment by xiaocq2001** [comment] 2024-04-19 03:36
Fix is in latest code. Can close.

**Closed** 2024-04-24 03:56 UTC
Labels: bug
